### ISSUE TITLE
Missing models in client

### ISSUE THREAD

**Issue by tapkation** [openshift/openshift-restclient-python#108]
When calling a delete_project() this is the error I get. 
After copying it manually from kubernetes modules, it continues to fail on other models in the deserializer.

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/vagrant/services/block-python/worker123/tasks/modules/openshift_cli.py", line 77, in del_proj
    api_response = self.api_instance.delete_project(name, pretty='false')
  File "/home/vagrant/services/block-python/venv/lib64/python3.6/site-packages/openshift/client/apis/oapi_api.py", line 14114, in delete_project
    (data) = self.delete_project_with_http_info(name, **kwargs)
  File "/home/vagrant/services/block-python/venv/lib64/python3.6/site-packages/openshift/client/apis/oapi_api.py", line 14198, in delete_project_with_ht
    collection_formats=collection_formats)
  File "/home/vagrant/services/block-python/venv/lib64/python3.6/site-packages/kubernetes/client/api_client.py", line 329, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/home/vagrant/services/block-python/venv/lib64/python3.6/site-packages/kubernetes/client/api_client.py", line 161, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/home/vagrant/services/block-python/venv/lib64/python3.6/site-packages/kubernetes/client/api_client.py", line 237, in deserialize
    return self.__deserialize(data, response_type)
  File "/home/vagrant/services/block-python/venv/lib64/python3.6/site-packages/openshift/client/api_client.py", line 16, in _ApiClient__deserialize
    klass = getattr(k8s_models, klass)
AttributeError: module 'kubernetes.client.models' has no attribute 'V1Status'

**Comment by fabianvf** [comment]
what versions of the openshift and kubernetes python packages do you have installed?

**Comment by tapkation** [comment]
Ohh.. Somehow openahift-python-client got in on top of openshift and kubernetes...  My bad
