### ISSUE TITLE
Can't configure openshift.client

### ISSUE THREAD

**Issue by cyril-dussert** [openshift/openshift-restclient-python#164]
Hello,

According to https://github.com/openshift/openshift-restclient-python/blob/master/openshift/README.md, I am trying to configure the openshit client with the following code:

```python
import openshift.client

openshift.client.configuration.username = 'OS_USERNAME'
openshift.client.configuration.password= 'OS_PASSWORD'
openshift.client.configuration.host= master.openshift.example.com

oapi = openshift.client.OapiApi()

openshift_request = oapi.list_user()
print(openshift_request)
```

This is just a code to test the restclient and I will use serviceaccount token afterwards for automatic authentication

But, when I am trying to run this code, I have the following error:

> AttributeError: module 'openshift.client' has no attribute 'configuration'

Do you have an idea of what I am missing? Do you have another approach to configure authentication?

> oc v3.7.23
> kubernetes v1.7.6+a08f5eeb62
> features: Basic-Auth GSSAPI Kerberos SPNEGO

> openshift-restclient-python v0.4.4

Thanks and regards,

**Comment by djzager** [comment]
I think that this may be a bug with our generated `README`. You should be able to do something along the lines:

```
import openshift.client

configuration = openshift.client.Configuration()
configuration.username = 'OS_USERNAME'
configuration.password = 'OS_PASSWORD'
configuration.host = 'master.openshift.example.com'

oapi = openshift.client.OapiApi()

openshift_request = oapi.list_user()
print(openshift_request)
```

**Comment by djzager** [comment]
Struggling to work through an example using `username` and `password` but I am able to see you will run into an issue with the `list_user()`:

```
>>> openshift_request = oapi.list_user()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "openshift/client/apis/oapi_api.py", line 18457, in list_user
    (data) = self.list_user_with_http_info(**kwargs)
  File "openshift/client/apis/oapi_api.py", line 18554, in list_user_with_http_info
    collection_formats=collection_formats)
  File "/tmp/osrcp/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/tmp/osrcp/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 163, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/tmp/osrcp/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 236, in deserialize
    return self.__deserialize(data, response_type)
  File "openshift/client/api_client.py", line 22, in _ApiClient__deserialize
    return super(ApiClient, self).__deserialize_model(data, klass)
  File "/tmp/osrcp/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 620, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "openshift/client/api_client.py", line 16, in _ApiClient__deserialize
    return super(ApiClient, self).__deserialize(data, klass)
  File "/tmp/osrcp/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 254, in __deserialize
    for sub_data in data]
  File "openshift/client/api_client.py", line 22, in _ApiClient__deserialize
    return super(ApiClient, self).__deserialize_model(data, klass)
  File "/tmp/osrcp/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 622, in __deserialize_model
    instance = klass(**kwargs)
  File "openshift/client/models/v1_user.py", line 68, in __init__
    self.groups = groups
  File "openshift/client/models/v1_user.py", line 142, in groups
    raise ValueError("Invalid value for `groups`, must not be `None`")
ValueError: Invalid value for `groups`, must not be `None`
```

@fabianvf is my resource on this. If I understand correctly this is either an issue with the swagger spec or with the generated client. You can work around that by doing something like:

```
>>> openshift_request = oapi.list_user(_preload_content=False)
>>> print(openshift_request.data)
{"kind":"UserList","apiVersion":"v1","metadata":{"selfLink":"/oapi/v1/users","resourceVersion":"23833"},"items":[{"metadata":{"name":"admin","selfLink":"/oapi/v1/users/admin","uid":"dab783ef-3cee-11e8-9e01-3a9caecf1ce1","resourceVersion":"1673","creationTimestamp":"2018-04-10T18:42:00Z"},"identities":["anypassword:admin"],"groups":null},{"metadata":{"name":"developer","selfLink":"/oapi/v1/users/developer","uid":"d997735b-3cee-11e8-9e01-3a9caecf1ce1","resourceVersion":"1574","creationTimestamp":"2018-04-10T18:41:58Z"},"identities":["anypassword:developer"],"groups":null}]}
```

**Comment by cyril-dussert** [comment]
Thanks for your hints, it seems that your solution permits to access the configuration

However, it looks like the config is not taken into account:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "/home/zbhn3817/Documents/git/kermit-portal-backend/kermit/api/customer_account.py", line 58, in put
    rest_client_get_user()
  File "/home/zbhn3817/Documents/git/kermit-portal-backend/kermit/openshift_actions/user.py", line 109, in rest_client_get_user
    openshift_request = oapi.list_user(_preload_content=False)
  File "/usr/local/lib/python3.5/dist-packages/openshift/client/apis/oapi_api.py", line 18457, in list_user
    (data) = self.list_user_with_http_info(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/openshift/client/apis/oapi_api.py", line 18554, in list_user_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/client/rest.py", line 205, in request
    headers=headers)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/request.py", line 66, in request
    **urlopen_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/poolmanager.py", line 321, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: /oapi/v1/users (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7efdb83559b0>: Failed to establish a new connection: [Errno 111] Connection refused',))
`

If I understood the error well, it tried to use localhost:443 as openshift cluster (which is not!) , but here is my config:
```python
def rest_client_get_user(username=None):
    os_client_config = openshift.client.Configuration()
    os_client_config.username = 'username'
    os_client_config.password = 'password'
    os_client_config.host = 'https://openshift.example.com'
    oapi = openshift.client.OapiApi()

    if username is None:
        openshift_request = oapi.list_user(_preload_content=False)
    else:
        openshift_request = oapi.read_user(name=username)
    print(openshift_request.data)
```

Thank you for your help

**Comment by BrianHolsen** [comment]
I tried the following and it worked. But list_user() function didn't, it said:
> module 'kubernetes.client.models' has no attribute 'V1UserList'


```python
import openshift.client

configuration = openshift.client.Configuration()
configuration.api_key_prefix = {'authorization': 'Bearer'}
configuration.api_key = {'authorization': 'YOUR TOKEN HERE'}

configuration.host = 'https://you_domain_name:8443'
configuration.verify_ssl = False
api_client = openshift.client.ApiClient(configuration=configuration)
oapi = openshift.client.OapiApi(api_client)

openshift_request = oapi.list_project()
print(openshift_request)
```

**Comment by djzager** [comment]
> module 'kubernetes.client.models' has no attribute 'V1UserList'

This suggests to me that you were using the Kubernetes client and not the OpenShift client. The snippet is trying to use `list_project`.

**Comment by Sispheor** [comment]
Ok I just placed my token in the "authorization" key of the api_key dict and it worked.

**Comment by Sispheor** [comment]
I reach the same error when trying to list all user. I use openshift client and not kubernetes

```python
# Configure API key authorization
configuration = openshift.client.Configuration()
configuration.api_key_prefix = {'authorization': 'Bearer'}
configuration.api_key = {"authorization": infras["staging"]["token"]}
configuration.host = infras["staging"]["url"]
configuration.verify_ssl = False

api_client = openshift.client.ApiClient(configuration=configuration)
oapi = openshift.client.OapiApi(api_client)
api_instance = openshift.client.UserOpenshiftIoV1Api(openshift.client.ApiClient(configuration))

# list users
openshift_request = api_instance.list_user()
print(openshift_request)
```

output
```
Traceback (most recent call last):
  File "/home/nico/Documents/kermit-portal-backend/venv/lib/python3.6/site-packages/openshift/client/api_client.py", line 16, in _ApiClient__deserialize
    return super(ApiClient, self).__deserialize(data, klass)
  File "/home/nico/Documents/kermit-portal-backend/venv/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 265, in __deserialize
    klass = getattr(models, klass)
AttributeError: module 'kubernetes.client.models' has no attribute 'V1UserList'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nico/Documents/kermit-portal-backend/venv/lib/python3.6/site-packages/openshift/client/api_client.py", line 16, in _ApiClient__deserialize
    return super(ApiClient, self).__deserialize(data, klass)
  File "/home/nico/Documents/kermit-portal-backend/venv/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 265, in __deserialize
    klass = getattr(models, klass)
AttributeError: module 'kubernetes.client.models' has no attribute 'V1User'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nico/Documents/kermit-portal-backend/nico.py", line 32, in <module>
    openshift_request = api_instance.list_user()
  File "/home/nico/Documents/kermit-portal-backend/venv/lib/python3.6/site-packages/openshift/client/apis/user_openshift_io_v1_api.py", line 1634, in list_user
    (data) = self.list_user_with_http_info(**kwargs)
  File "/home/nico/Documents/kermit-portal-backend/venv/lib/python3.6/site-packages/openshift/client/apis/user_openshift_io_v1_api.py", line 1731, in list_user_with_http_info
    collection_formats=collection_formats)
  File "/home/nico/Documents/kermit-portal-backend/venv/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/home/nico/Documents/kermit-portal-backend/venv/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 163, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/home/nico/Documents/kermit-portal-backend/venv/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 236, in deserialize
    return self.__deserialize(data, response_type)
  File "/home/nico/Documents/kermit-portal-backend/venv/lib/python3.6/site-packages/openshift/client/api_client.py", line 22, in _ApiClient__deserialize
    return super(ApiClient, self).__deserialize_model(data, klass)
  File "/home/nico/Documents/kermit-portal-backend/venv/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 620, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/home/nico/Documents/kermit-portal-backend/venv/lib/python3.6/site-packages/openshift/client/api_client.py", line 16, in _ApiClient__deserialize
    return super(ApiClient, self).__deserialize(data, klass)
  File "/home/nico/Documents/kermit-portal-backend/venv/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 254, in __deserialize
    for sub_data in data]
  File "/home/nico/Documents/kermit-portal-backend/venv/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 254, in <listcomp>
    for sub_data in data]
  File "/home/nico/Documents/kermit-portal-backend/venv/lib/python3.6/site-packages/openshift/client/api_client.py", line 22, in _ApiClient__deserialize
    return super(ApiClient, self).__deserialize_model(data, klass)
  File "/home/nico/Documents/kermit-portal-backend/venv/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 622, in __deserialize_model
    instance = klass(**kwargs)
  File "/home/nico/Documents/kermit-portal-backend/venv/lib/python3.6/site-packages/openshift/client/models/v1_user.py", line 68, in __init__
    self.groups = groups
  File "/home/nico/Documents/kermit-portal-backend/venv/lib/python3.6/site-packages/openshift/client/models/v1_user.py", line 142, in groups
    raise ValueError("Invalid value for `groups`, must not be `None`")
ValueError: Invalid value for `groups`, must not be `None`
```

**Comment by djzager** [comment]
The error you are seeing `"Invalid value for groups, must not be None"` is the reason we are moving to the dynamic client and deprecating the client you are using.

Here is an example using the dynamic client:

```
(osrcp) ➜  openshift-restclient-python git:(master) python
Python 2.7.15 (default, May 16 2018, 17:50:09)
[GCC 8.1.1 20180502 (Red Hat 8.1.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>> from kubernetes import client, config
>>> from openshift.dynamic import DynamicClient
>>>
>>> k8s_client = config.new_client_from_config()
>>> dyn_client = DynamicClient(k8s_client)
>>> users = dyn_client.resources.get(api_version='user.openshift.io/v1', kind='User')
>>> users.get()
ResourceInstance[UserList]:
  apiVersion: user.openshift.io/v1
  items:
  - groups: null
    identities: ['anypassword:admin']
    metadata: {creationTimestamp: '2018-06-11T13:04:31Z', name: admin, resourceVersion: '2305',
      selfLink: /apis/user.openshift.io/v1/users/admin, uid: fb1463d5-6d77-11e8-9170-54e1ad07cf60}
  - groups: null
    identities: ['anypassword:developer']
    metadata: {creationTimestamp: '2018-06-11T13:04:30Z', name: developer, resourceVersion: '2261',
      selfLink: /apis/user.openshift.io/v1/users/developer, uid: fa840f7c-6d77-11e8-9170-54e1ad07cf60}
  kind: UserList
  metadata: {resourceVersion: '18237', selfLink: /apis/user.openshift.io/v1/users}
```

Hope that helps.

**Comment by djzager** [comment]
My understanding is the original issue has been resolved.

**Comment by Sispheor** [comment]
The only way to get a config is to use a file?
We cannot use variables anymore?

Thanks for your help anyway.

**Comment by fabianvf** [comment]
@sispheor the configuration object is unchanged, djzager was just showing the shortest example of instantiating a dynamic client. Any instance of a kubernetes ApiClient will work no matter how it was configured.

**Comment by Sispheor** [comment]
Indeed it works.
Thanks again for your support guys !
