### ISSUE TITLE
pypi still points to 0.4.4 as latest release

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [openshift/openshift-restclient-python#169]
Since OpenShift 3.9 is out, can we have client 0.5? The latest seems to be 0.4.4 released on Feb 28th, 2018.

**Comment by djzager** [comment]
Thank you for pointing this out. https://github.com/openshift/openshift-restclient-python/tree/v0.5.0 created and should be pushed to pypi shortly.

**Comment by djzager** [comment]
https://pypi.org/project/openshift/ updated

**Comment by xunmeng-666** [comment]
@djzager 
When I run your code, IDE prompts the following error.
```
import openshift.client

configuration = openshift.client.Configuration()
configuration.username = 'OS_USERNAME'
configuration.password = 'OS_PASSWORD'
configuration.host = 'master.openshift.example.com'
oapi = openshift.client.OapiApi()
openshift_request = oapi.list_user()
print(openshift_request)


/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 /Users/xunmeng/Documents/projects/monitor/cloudfly/cloudfly_heketi/packaged/openshift.py
Traceback (most recent call last):
  File "/Users/xunmeng/Documents/projects/monitor/cloudfly/cloudfly_heketi/packaged/openshift.py", line 50, in <module>
    import openshift.client
  File "/Users/xunmeng/Documents/projects/monitor/cloudfly/cloudfly_heketi/packaged/openshift.py", line 50, in <module>
    import openshift.client
ModuleNotFoundError: No module named 'openshift.client'; 'openshift' is not a package
```

**Comment by xunmeng-666** [comment]
this code usr python3 on Mac OS and usr pip3 install openshift

**Comment by fabianvf** [comment]
I think you'd want

```python
from openshift import client
...
configuration = client.Configuration()
...
```
or 
```python
import openshift
...
configuration = openshift.client.Configuration()
...
```

**Comment by djzager** [comment]
0.6 has been released

**Comment by ravisantoshgudimetla** [comment]
Thanks @djzager for working on this. This was really helpful +1
