### ISSUE TITLE
Documentation should mention use of singular_name if resource search/get.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/openshift-restclient-python#303]
The docs use the example:

```
dyn_client.resources.get(api_version='v1', kind='ServiceList')
```

for looking up the resource object.

Problem is that there can be multiple names that map to the same type, which can result in a failure when one would not expect it.

```
>>> dyn_client.resources.get(api_version='template.openshift.io/v1', kind="Template")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/graham/Python/openshift/lib/python3.6/site-packages/openshift/dynamic/client.py", line 643, in get
    raise ResourceNotUniqueError('Multiple matches found for {}: {}'.format(kwargs, results))
openshift.dynamic.exceptions.ResourceNotUniqueError: Multiple matches found for {'api_version': 'template.openshift.io/v1', 'kind': 'Template'}: [<Resource(template.openshift.io/v1/processedtemplates)>, <Resource(template.openshift.io/v1/templates)>]
```

More prominence should be given in the documentation to using `singular_name` instead of `kind` when doing the look up.

```
>>> dyn_client.resources.get(api_version='template.openshift.io/v1', singular_name="template")
<Resource(template.openshift.io/v1/templates)>
```

Should also be highlighted though that singular name should be lower case though.

**Comment by GrahamDumpleton** [comment]
If singular name is also not guaranteed to be unique, the example should use both `kind` and `singular_name`.

```
>>> dyn_client.resources.get(api_version='template.openshift.io/v1', kind='Template', singular_name="template")
<Resource(template.openshift.io/v1/templates)>
```

**Comment by akostadinov** [comment]
Yes, resources from different kinds can have same name.
