### ISSUE TITLE
installation issue with pip

### ISSUE THREAD

**Issue by mattlegall** [openshift/openshift-restclient-python#402]
Hi,

My issue is likely to be simple but (as I have zero python knowledge) I don't know in which direction to search. Below is the error I am getting on the command line.

Thanks

[user@server ~]$ python
Python 2.7.5 (default, Jun 11 2019, 14:33:56)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()

[user@server ~]$ pip -V
pip 8.1.2 from /usr/lib/python2.7/site-packages (python 2.7)

[user@server ~]$ pip install openshift
Collecting openshift
  Using cached https://files.pythonhosted.org/packages/39/2b/7ff97fa8874de0d65f1bbb9c881eb0a40bf1c9b72a8ada187680758a61ee/openshift-0.12.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-VqceM_/openshift/setup.py", line 50, in <module>
        packages=find_packages(include='openshift.*'),
    TypeError: find_packages() got an unexpected keyword argument 'include'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-VqceM_/openshift/

**Comment by mattlegall** [comment]
No longer an issue
