### ISSUE TITLE
Problem pip installing openshift==0.13.0

### ISSUE THREAD

**Issue by AlanCoding** [openshift/openshift-restclient-python#425]
On Fedora 35 (and noticed in other CI pipelines)

```
$ pip install openshift==0.13.0
Collecting openshift==0.13.0
  Using cached openshift-0.13.0.tar.gz (19 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/alancoding/repos/awx/env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-slzp5yai/openshift_2f5bd857d0694b2691fef2a61cf32ca0/setup.py'"'"'; __file__='"'"'/tmp/pip-install-slzp5yai/openshift_2f5bd857d0694b2691fef2a61cf32ca0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-q410ksps
         cwd: /tmp/pip-install-slzp5yai/openshift_2f5bd857d0694b2691fef2a61cf32ca0/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-slzp5yai/openshift_2f5bd857d0694b2691fef2a61cf32ca0/setup.py", line 49, in <module>
        install_requires=extract_requirements('requirements.txt'),
      File "/tmp/pip-install-slzp5yai/openshift_2f5bd857d0694b2691fef2a61cf32ca0/setup.py", line 36, in extract_requirements
        with open(filename, 'r') as requirements_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/12/1d/914bfdcc8e1e3b9b88b050d77b934146831b5fe320ae238e3e1813e40fa5/openshift-0.13.0.tar.gz#sha256=af7cac828edacfdde637589ddb754aefab12f2fa7ad45c7c2075ff24bb6c2def (from https://pypi.org/simple/openshift/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement openshift==0.13.0 (from versions: 0.0.1, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4.0a1, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.7.0, 0.7.1, 0.7.2, 0.8.0a1, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.8.9, 0.9.0a1, 0.9.0a2, 0.9.0a3, 0.9.0a4, 0.9.0rc0, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0rc1, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.11.0, 0.11.1, 0.11.2, 0.12.0rc2, 0.12.0, 0.12.1, 0.13.0)
ERROR: No matching distribution found for openshift==0.13.0
WARNING: You are using pip version 21.2.3; however, version 21.3.1 is available.
You should consider upgrading via the '/home/alancoding/repos/awx/env/bin/python -m pip install --upgrade pip' command.
```

Looks like this was a really new release, https://pypi.org/project/openshift/#history, from 32 minutes ago, so sounds like this might be affecting multiple people.

**Comment by jadams** [comment]
`requirements.txt` is no longer included in setup.py

Please ref:  https://setuptools.pypa.io/en/latest/userguide/datafiles.html

Based on commit:  e61215defd52a740c46b2c31bd963861840abb30 by @fabianvf 

Also related is #403

From #403 format of data_files is creating a "requirements.txt" directory with the "requirements.txt" file inside of it

Ref: https://docs.python.org/3/distutils/setupscript.html#installing-additional-files

**Comment by kenmoini** [comment]
Also having issues with this update that is breaking different automation pipelines

**Comment by cryptarchnoble** [comment]
Likewise, has broken kubespray pipelines here. Pinning `openshift!=0.13.0` as @AlanCoding did in https://github.com/ansible/awx-operator/pull/782/commits/c95f3299b03cc6f79f4e6dd67ffaf474dfb46f5f as a workaround.

**Comment by geerlingguy** [comment]
Ditto, seems like all my CI tasks that install OpenShift have started failing this week.

**Comment by fabianvf** [comment]
oof :egg: :face_with_spiral_eyes: 

I should have known with such a strongly worded commit message I'd be completely wrong. 0.13.1 released and should fix it.

**Comment by geerlingguy** [comment]
> Useless cruft

Indeed! :D

**Comment by jadams** [comment]
Appreciate your work! Thanks for the quick fix
