### ISSUE TITLE
🐛  Exception on `apply` with `null` in current value and nested dict in desired

### ISSUE THREAD

**Issue by gabe-l-hart** [openshift/openshift-restclient-python#441]
## Description

When a field in the `kubectl.kubernetes.io/last-applied-configuration` annotation has the value set to `null`, an error will occur when attempting to call `apply` with a `desired` value that is not `null`.

I'm still diagnosing how we ended up with `"status": null` in the annotation, but I think the fix should be pretty straightforward.

**Stack Trace:**
```
Traceback (most recent call last):
  File "os_bug_repro.py", line 24, in <module>
    print(openshift.dynamic.apply.apply_patch(actual, desired))
  File "/opt/miniconda3/envs/caikit-runtime-stack-operator/lib/python3.8/site-packages/openshift/dynamic/apply.py", line 103, in apply_patch
    patch = merge(dict_merge(last_applied, annotate(last_applied)),
  File "/opt/miniconda3/envs/caikit-runtime-stack-operator/lib/python3.8/site-packages/openshift/dynamic/apply.py", line 139, in merge
    delta = get_delta(last_applied, actual, desired, position or desired['kind'])
  File "/opt/miniconda3/envs/caikit-runtime-stack-operator/lib/python3.8/site-packages/openshift/dynamic/apply.py", line 274, in get_delta
    p = get_delta(last_applied.get(k, {}), actual_value, desired_value, this_position)
  File "/opt/miniconda3/envs/caikit-runtime-stack-operator/lib/python3.8/site-packages/openshift/dynamic/apply.py", line 268, in get_delta
    if position:
AttributeError: 'NoneType' object has no attribute 'get'
```

## Repro

```py
import openshift.dynamic.apply
import json
import copy

prev_body = {
    "kind": "Foo",
    "apiVersion": "v42",
    "metadata": {
        "name": "foo",
    },
    "status": None,
}
prev_applied = json.dumps(prev_body)

actual = copy.deepcopy(prev_body)
actual["metadata"]["annotations"] = {"kubectl.kubernetes.io/last-applied-configuration": prev_applied}
actual["status"] = {"foo": {"something": "else"}}

desired = copy.deepcopy(prev_body)
desired["status"] = {"foo": {"something": "bar"}}

# This Raises
openshift.dynamic.apply.apply_patch(actual, desired)
```

**Comment by gabe-l-hart** [comment]
I'm pretty sure this can be fixed with some simple changes from `last_applied.get(k, {})` to `last_applied.get(k) or {}` in `get_delta` ([here](https://github.com/openshift/openshift-restclient-python/blob/master/openshift/dynamic/apply.py#L269)). This wouldn't handle the case where there's a type mismatch though.

```py
p = get_delta(last_applied.get(k) or {}, actual_value, desired_value, this_position)
```
