### ISSUE TITLE
Unable to use kube api/openshift api modules in tandem

### ISSUE THREAD

**Issue by bjpritch** [openshift/openshift-restclient-python#64]
I'm trying to create a simple script that can read from the Kubernetes API or Openshift API, depending on the model location. When loading and configuring both python modules in the same script, I'm unable to access the APIs independently without error.

Below are two examples to show what I'm trying:

```
#!/usr/bin/python

from openshift import client, config
import kubernetes

project = "myapp"

config.load_kube_config()
oapi = client.OapiApi()
kubernetes.config.load_kube_config()
api = kubernetes.client.CoreV1Api()

# Read OAPI
project_list = oapi.list_project()
for project in project_list.items:
    print project.metadata.name

# Read API
pod_list = api.list_namespaced_pod(project)
for pod in pod_list.items:
    print pod.metadata.name
```

Commenting out Read OAPI block or Read API block individually will work, but when both blocks are run I see the following output/error:

```
default
openshift-infra
myapp
Traceback (most recent call last):
  File "ocp_test.py", line 20, in <module>
    pod_list = api.list_namespaced_pod(project)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 12318, in list_namespaced_pod
    (data) = self.list_namespaced_pod_with_http_info(namespace, **kwargs)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 12417, in list_namespaced_pod_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 329, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 153, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 361, in request
    headers=headers)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/rest.py", line 240, in GET
    query_params=query_params)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/rest.py", line 231, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Date': 'Thu, 15 Jun 2017 14:56:36 GMT', 'Content-Length': '968', 'Content-Type': 'application/json', 'Cache-Control': 'no-store'})
HTTP response body: {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "User \"myapp-user\" cannot get origin', 'kubernetes']}, 'metadata': {'uid': '464d979f-c846-11e6-8ed3-001a4a1b5d67', 'labels': {u'zone': 'external'}, 'resourceVersion': '11994139', 'creationTimestamp': u'2016-12-22T12:58:03Z', 'annotations': {u'openshift.io/sa.scc.supplemental-groups': '1000090000 in project \"{'status': {'phase': 'Active'}, 'spec': {'finalizers': ['openshift.io\"",
  "reason": "Forbidden",
  "details": {
    "name": "requester': 'system:admin', u'openshift.io",
    "kind": "origin', 'kubernetes']}, 'metadata': {'uid': '464d979f-c846-11e6-8ed3-001a4a1b5d67', 'labels': {u'zone': 'external'}, 'resourceVersion': '11994139', 'creationTimestamp': u'2016-12-22T12:58:03Z', 'annotations': {u'openshift.io/sa.scc.supplemental-groups': '1000090000"
  },
  "code": 403
}
```

Another method I tried was to load the kube/openshift config separately, but this produced the same result (though with a different error):

```
#!/usr/bin/python

import kubernetes.client
import kubernetes.config
import openshift.client
import openshift.config

project = "myapp"

kubernetes.config.load_kube_config()
openshift.config.load_kube_config()

api = kubernetes.client.CoreV1Api()
oapi = openshift.client.OapiApi()

# Read OAPI
project_list = oapi.list_project()
for project in project_list.items:
    print project.metadata.name

# Read API
pod_list = api.list_namespaced_pod(project)
for pod in pod_list.items:
    print pod.metadata.name
```

Again, commenting a single read block and running will work, but running both produces the following error:

```
Traceback (most recent call last):
  File "ocp_test2.py", line 19, in <module>
    project_list = oapi.list_project()
  File "/usr/lib/python2.7/site-packages/openshift/client/apis/oapi_api.py", line 21012, in list_project
    (data) = self.list_project_with_http_info(**kwargs)
  File "/usr/lib/python2.7/site-packages/openshift/client/apis/oapi_api.py", line 21105, in list_project_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 329, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 161, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 237, in deserialize
    return self.__deserialize(data, response_type)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 271, in __deserialize
    klass = eval('models.' + klass)
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'V1ProjectList'
```

Is there an example that can be provided of loading/accessing both APIs at once?

**Comment by detiber** [comment]
@bjpritch I believe you are looking for something like this:
```
#!/usr/bin/python

from openshift import client, config
import kubernetes

oclient_config = config.new_client_from_config()
oapi = client.OapiApi(oclient_config)
kclient_config = config.new_client_from_config()
api = kubernetes.client.CoreV1Api(kclient_config)

# Read OAPI
project_list = oapi.list_project()
for project in project_list.items:
    project_name = project.metadata.name
    print(project_name)

    # Read API
    pod_list = api.list_namespaced_pod(project_name)
    for pod in pod_list.items:
        print(pod.metadata.name)
```
The issue you were hitting was related to using the global config object, which affects all clients. Another example is in the upstream client_python library for interacting with multiple clusters: https://github.com/kubernetes-incubator/client-python/blob/master/examples/multiple_clusters.py

**Comment by chekolyn** [comment]
I have a function for this purpose looks something like this, it returns a tuple with the clients:

```
def get_apis_clients(context=""):
    """
    Returns a tuple with K8s api and OpenShift api clients: 
    :param context: The context in the kube config file  
    :param file: 
    :return: tuple of api clients
    """
    # Get config:
    config = get_config()

    kube_config_file = config.get("KubeConfig", "path")
    config_client = oconfig.new_client_from_config(config_file=kube_config_file, context=context)
    api = kc.CoreV1Api(config_client)
    oapi = oc.OapiApi(config_client)

    return api, oapi
```
