### ISSUE TITLE
The tar.gz source package on PyPi is broken and can't be installed.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/openshift-restclient-python#70]
When installing ``openshift`` package with version of ``pip`` that does't support wheels, or if use of wheels is disabled, the ``tar.gz`` source package on PyPi will fail to install.

```
$ pip install --no-use-wheel openshift
DEPRECATION: --no-use-wheel is deprecated and will be removed in the future.  Please use --no-binary :all: instead.
Collecting openshift
  Downloading openshift-0.0.1.tar.gz (245kB)
    100% |████████████████████████████████| 256kB 808kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0p/4vcv19pj5d72m_bx0h40sw340000gp/T/pip-build-mNQ8Py/openshift/setup.py", line 49, in <module>
        install_requires=extract_requirements('requirements.txt'),
      File "/private/var/folders/0p/4vcv19pj5d72m_bx0h40sw340000gp/T/pip-build-mNQ8Py/openshift/setup.py", line 36, in extract_requirements
        with open(filename, 'r') as requirements_file:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/0p/4vcv19pj5d72m_bx0h40sw340000gp/T/pip-build-mNQ8Py/openshift/
```

This is because you haven't specified a ``MANIFEST.in`` file to list what extra files should be included in the source distribution package, such as ``requirements.txt``.

**Comment by fabianvf** [comment]
Is this fixed with #71?
